apiVersion: v1
kind: Pod
metadata:
 name: blue-pod
 annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "k8s-default", "name":"k8s-blue-net-pod-network"}'
  }
spec:
 containers:
   - name: ubuntuapp
     image: ubuntu-upstart
