apiVersion: v1
kind: Pod
metadata:
 name: multi-intf-pod
 annotations:
   k8s.v1.cni.cncf.io/networks: '[
     { "name": "red-net" },
     { "name": "green-net" }
   ]'
spec:
 containers:
   - name: ubuntuapp
     image: ubuntu-upstart
