apiVersion: v1
kind: ReplicationController
metadata:
  name: np-example 
spec:
  replicas: 3
  selector:
    app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: savvythru/contrail-frontend-app
        ports:
        - containerPort: 80
