apiVersion: v1
kind: Pod
metadata:
  name: ubuntuapp
  labels:
    app: ubuntuapp
spec:
  containers:
    - name: ubuntuapp
      image: ubuntu-upstart
      command: ["/bin/bash","-c","while true; do sleep 10;done"]
